### ISSUE TITLE
RTE on startup

### ISSUE THREAD

**Issue by silvertoad** [TiVo/intellij-haxe#140]
I'm update plugin from Jetbrains repository and can't open haxe module.
full log: https://gist.github.com/silvertoad/0038af853aab778d7bb2

**Comment by jasonsturges** [comment]
@silvertoad IntelliJ 14.0.3 is not yet support, per #139 - it's frustrating, especially given no release notes regarding it combined with its destructive force on IntelliJ IDEA.

**Comment by EBatTiVo** [comment]
His log clearly shows "Unsupported major.minor version 51.0", which means he is running IDEA under Java 6, and the one in JetBrains repository had been recompiled using Java 1.7.  That has been updated this morning, so it should run.  

That said, don't run it with IDEA 14.  That it was picked up automatically by IDEA 14 should be fixed this morning also: according to Boyan, he marked the new release as 13-only so that IDEA 14 users pick up the old one from the JetBrains IDEA repository.

@jasonSturges - As for the plugin's "destructive force," it would be great if you could tell us what happened to your projects (in Issue #18, or a new issue, if you prefer)  when you installed it.  I expected that it wouldn't run correctly, but I did NOT expect it to corrupt projects, sources, etc..

**Comment by sganapavarapu1** [comment]
@jasonsturges - 
When I first installed the incorrectly built plugin yesterday, I experienced similar stuff other users complained i.e. cannot see my modules or project hierarchy. I was concerned as well, if I lost any files or project definition / meta files. 

But I realized that everything was in-tact, like EBatTiVo mentioned. Because plugin could not be loaded, I was not seeing the contents of any 'haxe' project or 'haxe' sdk. I uninstalled that incorrect version.

Once I installed correct version of intellij-haxe plugin, 0.9, released earlier today - everything is normal.

**Comment by jasonsturges** [comment]
@sganapavarapu1 @EBatTiVo Thanks, I'll check out 0.9 released today; however, my interest is waning until IntelliJ IDEA 14 is supported.  

Since IntelliJ IDEA 14 is not yet supported, I presume development will expose the current issues.  There are tickets I've logged and participated in, such as #67 in which the plugin froze IntelliJ to an unusable state, which has been labeled an enhancement for some reason.  Many tickets here could probably be closed per #18.

Definitely appreciate your extending use of Haxe plugin beyond TiVo to the community.

**Comment by as3boyan** [comment]
@jasonsturges I released alpha for IntelliJ IDEA 14

**Comment by jasonsturges** [comment]
@as3boyan Thanks for letting me know - is that under the ClassHierarchy branch?  I don't see a prerelease.

**Comment by EBatTiVo** [comment]
@jasonsturges - He released it on the JetBrains repository: http://plugins.jetbrains.com/plugin/6873?pr=idea
It isn't fully checked into any of the TiVo trees or the JetBrains github repo yet.

**Comment by as3boyan** [comment]
@jasonsturges https://twitter.com/As3Boyan/status/576068981699772416/photo/1

**Comment by jasonsturges** [comment]
@as3boyan @EBatTiVo Cool - it installed, and looks good at first glance although I can't compile or run.  Thanks for the heads up - I will continue to monitor the alpha releases from JetBrains repositories.

**Comment by as3boyan** [comment]
@jasonsturges It compiles flixel project for me.
![Imgur](http://i.imgur.com/YGIPvOa.png)
Starts flash player fine if run without debug.

>Flash target: Debugger never attaches. Plugin and projector content debugger is installed. Maybe I have the wrong port (6972). Also OpenFL argument never persist - when I close the Project Structure dialog and reopen it, my previously entered values are lost. I've added argument -debug.

This is still happens, the only workaround for it I know is enabling separate compilation in project options.

I also tested on Haxe/Neko project - compiles fine, runs in terminal.

Please specify your project type/configuration.

Also, it's wierd that IDEA/plugin copies source files to production folder

**Comment by jasonsturges** [comment]
OpenFL project, which compiles / runs from the command line; however, plugin 0.9.2 gives me:

![image](https://cloud.githubusercontent.com/assets/1213591/6654486/4570128c-ca96-11e4-98e5-86af826ce236.png)

Since IntelliJ IDEA 14 support is alpha, I'll try to do some rounds of testing if I get some time.  Thanks.

**Comment by as3boyan** [comment]
I think warnings should be replaced with real command if possible

**Comment by EBatTiVo** [comment]
@as3boyan I don't understand what you mean by the previous comment.

The fake warning has nothing to do with the error that @jasonsturges is seeing.  The real error is showing up properly.

That said, the error seems to be that haxelib (or whatever is actually executing) doesn't support the "run" command.  That makes me think that the command we're trying to execute isn't formatted correctly.  Perhaps we should always echo the command we're running as an information line to the compile output.
