### ISSUE TITLE
Toggle case for word behavior is incorrect.

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#211]
Switching case for word (⇧⌘X) changing case for:
- all comment instead one word;
- code-lines near of comment;

![u-d-case mov opt](https://cloud.githubusercontent.com/assets/888526/6996533/0ef67e24-db96-11e4-8f78-61572a0b3e66.gif)

TIR: STB-9372

**Comment by as3boyan** [comment]
Sorry, I don't get what do you expect and what problem you have.

**Comment by EBatTiVo** [comment]
The problem that I see is that toggle case selects an entire code block -- instead of the word under the cursor -- if there is no selection.  It appears to work correctly when there is already a selection.

**Comment by as3boyan** [comment]
I think that it should be fixed, at moment when I added PsiComment to HaxeASTFactory

**Comment by as3boyan** [comment]
@EBatTiVo Expand Selection(Ctrl-W) on comment + Uncommenting multiline comment block didn't worked properly, probably because all tokens were

Also, workaround I made for `Useful.....isWhitespaceOrComment` may be commented or removed, because now it should be able to compare tokens with `PsiComment`

**Comment by EBatTiVo** [comment]
That was released in 0.9.3.  @fzzr- Can you please test this and close the bug if it's fixed?

**Comment by fzzr-** [comment]
Works correctly in latest release. Thx!

**Comment by EBatTiVo** [comment]
fzzr- tested this a while back, so closing...
