### ISSUE TITLE
Error during Ant Build using IntelliJ IDEA 13.1.6

### ISSUE THREAD

**Issue by as3boyan** [TiVo/intellij-haxe#250]
Error during Ant Build using IntelliJ IDEA 13.1.6
605785a4cbee4733d21189eba9692c744a9a7477

http://imgur.com/hbk6HML

**Comment by EBatTiVo** [comment]
OK.  So this isn't an issue of code.  It's an issue of updating your project structure.  Since all of the versions exist in a single source base, the project must be set up correctly.  We decided to make the default settings be correct for v14.1.  However, to build other builds, you can either use the ant builds (install the ant plugin, add the xml files from the root directory, and select "package"; or build ant from the command line 'ant -Didea.ultimate.build=<path_to_idea_installation>'), or you can change the project structure to match the environment you're trying to build.

So, for 13.1.6, change this:
![image](https://cloud.githubusercontent.com/assets/7231977/7262702/836e9f6a-e830-11e4-80f6-34a4d3bf6d9a.png)
to this:
![image](https://cloud.githubusercontent.com/assets/7231977/7262731/aaecc846-e830-11e4-9701-62c65578489e.png)

Then try to rebuild.

Unfortunately, IDEA will not allow multiple .iml files with the same project root, so we can't have a configuration for each build type.

I do have an idea that I haven't tried: Use ant to update the project file with this change (using either javascript or a custom task).  We would do that by finding the appropriate directories in the .iml file and changing the attributes as appropriate.  Then we would cause this new task to be run at every compile (or, really, just add it as a dependency to metainf, which already runs for each compile).

I guess this is yet another subject for the README.md.

**Comment by EBatTiVo** [comment]
OK, I looked at the file you provided and thought I was seeing a regular build.  No.  I was wrong.   So...

Idea installation not found.  If you open up the failure line, it has an explanatory message, telling you  what directory it thinks that idea is installed in (or none at all) and what to do about it:
```
    IDEA installation not found.

    Either '${idea.ultimate.build}' does not exist, or it does not appear
    to be a normal IDEA installation.  (It should contain a build.txt file.)
    See the description section at the top of this file (common.xml) for more
    information.

    You can tell this build where to find to your IDEA Ultimate build directory
    by adding "-Didea.ultimate.build=path_to_your_IDEA_installation" to the
    command line, where path_to_your_IDEA_installation is a directory on your
    local machine.

    Alternately, you can run this build by executing the build.sh file in the
    project root directory, which will fetch a new installation for you.
```

The algorithm works like this:
  Pick the *first* instance of idea.ultimate.build that is set from the following locations (in order):
    - the command line (e.g. includes ```-Didea.ultimate.build=<path>```)
    - local-build-overrides.xml file
    - the grandparent directory from which ant is running, if ant is running from (${ant.home} is set to) a directory named **/lib/ant and the file build.txt exists in the grandparent directory.
    - <project_root>/idea-IU/

Once the idea.ultimate.build property is set, the existence of build.txt is checked.  If build.txt cannot be found, then the error message you see above is displayed.

In order to get the above message while running inside of IDEA, your build.txt file must be missing, or you must have overridden IDEA's default ant installation.  Idea ships with an ant installation and that is normally what is used when running ant builds -- thus the check for ${ant.ho0me}/../../build.txt.

You can either restore the ant defaults inside of idea, or add a property entry to local-build-overrides.
```    <property name="idea.ultimate.build" value="/home/boyan/intellij_idea/idea-IU-135.1286"/> ```

In any case, build.txt MUST exist in your installation directory.  If it does not exist, then you can create one.  It is a single line file with the following format:
* two character product prefix  (e.g. IU for IDEA Ultimate, IC for community edition, and so on)
* a dash ("-")
* code line ID  (e.g. 135 for IDEA 13.1, 139 for  IDEA 14, 141 for IDEA 14.1)
* a dot (".")
* build number (e.g. 1286)
* optionally,
  * a dot
  * iteration number

Example:
```      IU-135.1286 ```
or
```      IC-141.1117.8 ```

**Comment by EBatTiVo** [comment]
Waiting for Boyan to check his setup and report back.

**Comment by as3boyan** [comment]
>You can either restore the ant defaults inside of idea, or add a property entry to local-build-overrides.
<property name="idea.ultimate.build" value="/home/boyan/intellij_idea/idea-IU-135.1286"/>

I should create `local-build-overrides.xml" in project root?

**Comment by as3boyan** [comment]
>- the command line (e.g. includes -Didea.ultimate.build=<path>)

ant -Didea.ultimate.build=<path>? Where I can add this?

**Comment by as3boyan** [comment]
Maybe something like https://weblogs.java.net/blog/schaefa/archive/2005/01/how_to_do_condi.html could work as conditional compilation?

**Comment by as3boyan** [comment]
Ok, I added local-build-overrides.xml file, seems to work fine for IDEA 13.1.6

**Comment by EBatTiVo** [comment]
> Maybe something like https://weblogs.java.net/blog/schaefa/archive/2005/01/how_to_do_condi.html could work as conditional compilation?

Once I figured out how to detect the IDEA SDK, it was a short leap to figuring out how to generate a java file that creates constant booleans for conditional compilation.  Then we can just put code into blocks like this:
```java
  if (IDEA_SDK_VERSION_IS_13) {
    // Do v13-specific work
  } else if (IDEA_SDK_VERSION >= RELEASE_14) {
    // Use newer apis
  } else {
   // Error or common code
  }
```
It's going to be trickier for the 'implements' vs 'extends' changes, but I think I've got a pattern (something like the delegator pattern) that will work.  I need to experiment, though, and I haven't gotten the time yet.

**Comment by EBatTiVo** [comment]
Added the content from the comments of this bug, as well as some other process documentation that we had on email threads to the README.md and CONTRIBUTING.md files.
