### ISSUE TITLE
Why does the readme say, one needs the ultimate edition of intellij

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [TiVo/intellij-haxe#332]
I am using the community edition, and it works. Am I missing something?

**Comment by EBatTiVo** [comment]
As a practical matter, most IDE functionality will work just fine.  Using CE, you probably don't use the Hierarchy (Ctrl+H) or diagram facilitities (Ctrl+Alt+U).  I don't test CE, so I can't say whether the features are disabled or not.  However, if the features are enabled and you try to use them, you will get NPEs, because they use functions that are only available in the Ultimate jars.

Secondly, we (TiVo) don't build or test against CE at all (though we do use the sources to help us debug).  So, from a development perspective we don't support it, either.  Bugs can be filed and will be managed, but if they do not occur on the Ultimate edition, they will require wider community involvement to be addressed.  This is also true for using the plugin with other JetBrains IDEA offshoot products, such as AppCode, CLion, RubyMine, et cetera.
