### ISSUE TITLE
Navigate symbol does not work

### ISSUE THREAD

**Issue by RealyUniqueName** [TiVo/intellij-haxe#340]
Navigating symbols does not work for me. Is it implemented? Or maybe something in my setup blocks it?
When i open navigation panel there are no symbols listed.
Default keybinding: Ctrl+Alt+Shift+N

**Comment by EBatTiVo** [comment]
Please give us instructions to duplicate the bug exactly, including expected and actual results.  Also include version information for IDEA, the plugin, your OS, and JRE.

Navigation of symbols is implemented and based on completion (indexing must finish correctly in order to populate the completion database).  However, you must type something (the beginning of a symbol name) into the text box before anything is shown; it is not possible to get a list of all symbols merely by opening the dialog.

**Comment by RealyUniqueName** [comment]
Ubuntu 14.04 x64
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
Intellij IDEA 14.1.4 Community Edition (build IC-141.1532.4 )
Haxe plugin version 0.9.5 for IDEA 14.1.3
No other plugins installed except those installed with IDEA by default.

Steps to reproduce:
1. Create new Haxe project
2. Create new Haxe class.
3. Add any method.
4. Open symbol navigation panel.
5. Start typing the name of previousely created method.
At this point the list of symbols is empty.

**Comment by eliasku** [comment]
PR #445 
![navigatetosymboldemo](https://cloud.githubusercontent.com/assets/3038174/13422735/a50fb5ae-dfa7-11e5-87cf-a42b3c60d397.gif)

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/edc202d3172005421b0e602e3af666eb5ef27d5e
