### ISSUE TITLE
Interface glyph causing gutter to change widths, results in screen flicker 

### ISSUE THREAD

**Issue by alagatar** [TiVo/intellij-haxe#361]
I found annoying issue while write haxe code using intellij-haxe plugin.
When you write code in method that overrides parent method and put some glyph in gutter area show override icon and than hide, this shift all screen right than left, screen flicker.
I found old bug in Intellij Idea https://youtrack.jetbrains.com/issue/IDEA-50006, there looks like this bug present becouse frequence change AST of code

**Comment by alagatar** [comment]
Hi, I will be happy receive any information about this issue, may be temp method how fix this?
Thanks for your work!

**Comment by EBatTiVo** [comment]
I'm not sure whether this is a bug.  When an override is introduced, yes, the gutter widens to denote that.  (And I can find no setting to turn that off.)  If you continue typing and change the characteristics of the function so that there is no override, the gutter returns to its normal size to give more view space to the code being edited.  That sounds like proper (if ugly) behavior.

Do you see this behavior when working with Java or C++?

It may be possible to permanently set the gutter wide enough to accommodate all icons.  There is no setting (in IDEA 14.1) to do so, however, so it would mean a code change -- one that's probably not in plugin code.

There are other potential solutions, such as introducing delays to reduce flicker, or removing the notification altogether.  It all depends upon the code that puts up the icon and where it's triggered from.  I haven't had the time to take a look.

If I have mischaracterized the actions that lead to the issue, please provide a more complete description.

**Comment by alagatar** [comment]
I send bug to jetbrains. Now it fixed in build 144.2461 (this is in eap now, idea 16, webstorm 12).
