### ISSUE TITLE
Version 0.9.9 is incompatible with IntelliJ IDEA 2016

### ISSUE THREAD

**Issue by giuppe** [TiVo/intellij-haxe#454]
I updated my IntelliJ IDEA to 2016.1, and then the Haxe plugin (0.9.9) was disabled as not compatible, asking me to downgrade to 0.9.7 for IDEA 14. I downgraded, but the plugin is still not compatible.

**Comment by JB-Tellez** [comment]
Same for me with IDEA 2016. IntelliJ lets you have older version installed so I'm running IDEA 14 alongside IDEA 2016 as a workaround.

**Comment by EBatTiVo** [comment]
Actually, the plugins are marked as compatible with a given set of releases, based upon the code line and build number.  Many people in EAP were having issues with running the plugin in newer (generally, unreleased) versions on IDEA.  To minimize the confusion and let people know that the plugin wasn't known to be compatible, we limited the markings to released code lines.  The old v14 releases weren't all marked that way, so they continue to be installable even though they don't work well in v15 onward.

We certainly want to release a v16 version, but don't have the resource available right now.  There are a number of changes, including the compiler level required (Java 8 vs Java 6).  Therefore it's not a simple matter of changing the markings and releasing.  We have to update the build environment(s) as well as fix the the normal litany of breaking changes.  We probably need more rigorous testing, too.  Are you interested in helping?

**Comment by EBatTiVo** [comment]
BTW, you can also run IDEA v15 alongside v16, so you can run the 0.9.9 release of the plugin there.  Though we are slowly moving that direction, for our purposes, TiVo hasn't seen a compelling reason to upgrade to v15 yet, let alone v16.

**Comment by JB-Tellez** [comment]
Makes sense about the listed Compatible Builds. So I wasn't figuring that plugin would work with v16 for a while. I'd be happy to bug test when you release a v16 candidate. Thanks!

**Comment by dmouton** [comment]
:+1:

**Comment by laurence-myers** [comment]
@EBatTiVo I'd be willing to try and help implement the changes, though I have no experience with JetBrains plugin dev. Is there list of tasks you need done, or a changelog of differences between IDEA plugin APIs?

**Comment by EBatTiVo** [comment]
I've actually done most of the bookkeeping tasks: new properties files, new constants, etc.  The only thing left for me to do in the ant scripts is to make the target JDK change based upon the releases (IDEA 14 & 15 require JDK 6, while IDEA 16 requires JDK 8).  See the v16_BuildSupport branch.

But that's all the easy stuff.  Working through the build differences, and coming up with multi-release compatible source changes (by using reflection, etc.) is the hard part.  There is no list of APIs that changed and need repair, per se.  We can get all of that from github (IDEA 143 and 145 code lines from the github.com/jetbrains/intellij-community repo -- look at their tags to find releases), but there is no consolidated list of API changes.  So, it's really "just try it and see what breaks."

I have tried to build the plugin against the v16 plugin dev kit targeting the 1.6 JRE, and it will not even start.  By changing the target JRE to 1.8 (in the IDEA compiler settings), I was able to get to seeing build errors in tests, which is the last to build, so we may be really close, actually.  

I got stopped by some CodeInsight classes changing packages.  It turns out that the specific package -- DefaultHighlightVisitorBasedInspection -- is normally loaded in IDEA via the globalInspection "Annotator" interface.  I was looking into using that to find the class, but I don't think it will work, given how we use it.  

So, we're going to have to use reflection to load the class from the proper packages:  We need a new com.intellij.plugins.haxe.build.ClassWrapper class that can do the lookup, and has an Allocate(Object... args) (or New, or Create) function that will basically return a newly allocated class using the given arguments.  The we need to add a new function that replaces the 'new DefaultHighlightVisitorBasedInspection.AnnotatorBasedInspection()' and used the new class along with the constants in IdeaTarget to decide which class to load.  src/common/com/intellij/plugins/haxe/build/IdeaTarget has the constants.  .../MethodWrapper is one example to pattern the new ClassWrapper function off of,  There are a few examples that already use MethodWrapper() that may be helpful.

**Comment by laurence-myers** [comment]
Phew, is that all? ;)
I haven't looked at how MethodWrapper works, but wouldn't any solution need to be compiled against both versions of the SDK? The only way I know to support that is to use an interface + wrapper/adapter to encapsulate the problem class, then have separate JARs that provide the implementation required (depending on a build flag). I wondered if seeing how something like Spring Boot handles optional dependencies would be useful.
Are the changes you've already made available in a branch?

**Comment by EBatTiVo** [comment]
The changes up to this point are available in the v16_BuildSupport (https://github.com/TiVo/intellij-haxe/tree/v16_BuildSupport) branch.

MethodWrapper and FieldWrapper work basically like you describe: they add a new class to encapsulate the underlying API/field, which then loads the appropriate method/field via reflection, doing a little type and parameter verification along the way.  When the method/field is needed, it is retrieved/called via the wrapper class.

We always build four separate builds for different versions of the SDK (14.0.x, 14.1-4, 14.1.5+, and 15.x).  I keep most of the releases readily available on my machine so that I can just add a -Dversion=<number> to the ant build script.  I've added a local-build-overrides.txt as described in common.xml to manage them and select my target SDK at build time.

**Comment by EBatTiVo** [comment]
BTW, the 'separate jars' with the underlying implementation, such as you describe, are the individual releases of IDEA.  We don't need to supply them, we just have to look the implementations up and call them.

**Comment by indolering** [comment]
I really wish IntelliJ would throw some resources behind this plugin!

**Comment by eliasku** [comment]
@giuppe @JB-Tellez @dmouton try this one: https://github.com/eliasku/intellij-haxe/releases/tag/v0.10.0-beta

**Comment by demurgos** [comment]
Hi, I know that this is an old issue, but is there some support about supporting the current version of IntelliJ ? I understand that this is a lot of work, but I really hope that this plug-in will keep working.

**Comment by EBatTiVo** [comment]
The pre-release supports 2016.x (https://github.com/TiVo/intellij-haxe/releases/tag/0.10.1-rc2).  I am about to release it.  We've been getting some good bug fixes every couple of days, though, and I haven't had time to actually smoke test it on all of the supported versions of IDEA (takes about four hours), so it's been in a sort of holding pattern.  In the mean-time, you can download the pre-release.

**Comment by demurgos** [comment]
Thank you for the information, I'll try it.

**Comment by demurgos** [comment]
@EBatTiVo 
I am using the version you linked above and did not encounter any breaking issue for the moment. Even if I know now how to install the correct version manually, it would be nice if it was published so it could be installed from the IDE (it would also "reset" the time since the last update and signal that this plugin is still active.

Are there some compatibility issues with this version that I am not aware of ? Maybe they have a tag ?
If you could explain me the blocking issues to publish the new version I could try to look at them (I don't know much about plugin development but if these are simple issues I could help)

**Comment by EBatTiVo** [comment]
@demurgos - Ah.  Yes.  I've been on the cusp of a release for a month now.   :-/

A release is very high on my priority list.  The only thing that has been keeping me from it is getting the time to smoke test it and prep the release, which takes a few hours.  Your having tested it and letting me know saves me some of that effort, so I'm quite pleased that you've done so.

**Comment by EBatTiVo** [comment]
@demurgos - Release has been made. 0.10.1 is fully compatible with all versions of IDEA 2016.x.

**Comment by demurgos** [comment]
Sorry to bother you, but I am unable to install it from the IDE:

- I see that you published the latest version to the repository: https://plugins.jetbrains.com/idea/plugin/6873-haxe-support
- In the IDE, it only displays the version from the 11/4/2015: https://i.imgur.com/5SY9GR8.png

Do you also have this issue is this a problem on my side ? Did you know how I can "refresh" the list of plugins ?

**Comment by EBatTiVo** [comment]
@demurgos - And, of course, I tested it on 2016.3.1, which works.  2016.3.2 has a build number that is greater than 9999, which is why it doesn't work.  It will take me a couple of hours, but I'll get that out and working.
