### ISSUE TITLE
Add support for string literals for the keys in structures

### ISSUE THREAD

**Issue by winmain** [TiVo/intellij-haxe#498]
I use Haxe to generate Javascript code & sometimes I have to use string literals in JSON stuctures (https://haxe.org/manual/types-structure-json.html).

This code breaks parser:
```haxe
class Test {
  var a = {
    'singleQuotes': 1,
    "doubleQuotes": 2
  };
}
```
I think there need to do some BNF tuning.

Plugin version: `Pre-release candidate 0.10.1-RC1`
Idea: `2016.2`

**Comment by EBatTiVo** [comment]
@winmain Do you have this working on your fork?  Is it ready for a PR?

**Comment by winmain** [comment]
Not quite. I have almost working build (enough for myself), but not for Idea 14.0.5: https://travis-ci.org/winmain/intellij-haxe/builds/167235869

**Comment by EBatTiVo** [comment]
@winmain At a guess, it might work if you used 14.0.5 to generate the parser, rather than a newer build.  It looks like 14.0.5 doesn't have the begin_section() and end_section() with the proper parameters.  An older parser generator wouldn't have that problem... but it might not have some of the newer fixes if your changes rely on those.

BTW, what version of IDEA and Grammar-kit are you using to generate the parser and gen/ tree?

**Comment by winmain** [comment]
It's a good idea. I used latest IDEA 2016.2.4 & latest Grammar-kit plugin. But I will try to rebuild classes on 14.0.5 later.

**Comment by winmain** [comment]
Ok, I did it with Idea 14.0.5 & Grammar plugin 1.2.0.1. Will make PR
