### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by WeyskoteFoundation** [TiVo/intellij-haxe#92]
![haxe](https://cloud.githubusercontent.com/assets/4976223/5554571/78d2f5c6-8c49-11e4-9e3a-d171799a2a2b.png)

**Comment by EBatTiVo** [comment]
What was the bug here?  That the second ```#if php``` gave a compiler error?  That appears to be fixed in Build 0.8.1.1.TiVo.ClassHierarchy.11.  So, I'm closing this bug.

Note that the example now gives a "duplicate class" error at the second definition of Twig_Environment (Issue #54).  Unfortunately, that is the way it has to be for now.  We don't have a good way to check multiple paths through pre-processing symbols.  See the discussion on Issue #38 and Issue #54 for some more context.
